/*
 * MIDDLE_FLexCAN.h
 *
 *  Created on: Nov 4, 2024
 *      Author: adm
 */

#ifndef INCLUDE_MIDDLE_FLEXCAN_H_
#define INCLUDE_MIDDLE_FLEXCAN_H_

#include "FlexCAN.h"

typedef enum
{
	/* Defines for MBx callback */
	MIDDLE_HANDLER_MB_0_TYPE		= 0U,
	MIDDLE_HANDLER_MB_1_TYPE,
	MIDDLE_HANDLER_MB_2_TYPE,
	MIDDLE_HANDLER_MB_3_TYPE,
	MIDDLE_HANDLER_MB_4_TYPE,
	MIDDLE_HANDLER_MB_5_TYPE,
	MIDDLE_HANDLER_MB_6_TYPE,
	MIDDLE_HANDLER_MB_7_TYPE,
	MIDDLE_HANDLER_MB_8_TYPE,
	MIDDLE_HANDLER_MB_9_TYPE,
	MIDDLE_HANDLER_MB_10_TYPE,
	MIDDLE_HANDLER_MB_11_TYPE,
	MIDDLE_HANDLER_MB_12_TYPE,
	MIDDLE_HANDLER_MB_13_TYPE,
	MIDDLE_HANDLER_MB_14_TYPE,
	MIDDLE_HANDLER_MB_15_TYPE,
	MIDDLE_HANDLER_MB_16_TYPE,
	MIDDLE_HANDLER_MB_17_TYPE,
	MIDDLE_HANDLER_MB_18_TYPE,
	MIDDLE_HANDLER_MB_19_TYPE,
	MIDDLE_HANDLER_MB_20_TYPE,
	MIDDLE_HANDLER_MB_21_TYPE,
	MIDDLE_HANDLER_MB_22_TYPE,
	MIDDLE_HANDLER_MB_23_TYPE,
	MIDDLE_HANDLER_MB_24_TYPE,
	MIDDLE_HANDLER_MB_25_TYPE,
	MIDDLE_HANDLER_MB_26_TYPE,
	MIDDLE_HANDLER_MB_27_TYPE,
	MIDDLE_HANDLER_MB_28_TYPE,
	MIDDLE_HANDLER_MB_29_TYPE,
	MIDDLE_HANDLER_MB_30_TYPE,
	MIDDLE_HANDLER_MB_31_TYPE,

	/* Defines for ERROR and ORED callback*/
	MIDDLE_HANDLER_ERROR_TYPE,
	MIDDLE_HANDLER_ORED_TYPE
}Middle_FlexCAN_Handler_e;

void Middle_FlexCAN_Init(FlexCAN_Instance_e Ins);
void Middle_FlexCAN_DeInit(FlexCAN_Instance_e Ins);
void Middle_FlexCAN_SetCallback(FlexCAN_Instance_e Ins, Middle_FlexCAN_Handler_e HandlerType, FlexCAN_CallbackType HandlerFunc);
void Middle_FlexCAN_StandardTransmitMbInit(FlexCAN_Instance_e Ins, FlexCAN_MbIndex_e MbIndex, uint32_t ID, bool Interrupt);
void Middle_FlexCAN_StandardReceiveMbInit(FlexCAN_Instance_e Ins, FlexCAN_MbIndex_e MbIndex, uint32_t ID, bool Interrupt)

#endif /* INCLUDE_MIDDLE_FLEXCAN_H_ */
